### ISSUE TITLE
Standard way to link to parts of my project

### ISSUE THREAD

**Issue by jmacarthur** [opencontrol/schemas#51]
We've been reviewing OpenControl, apologies if I missed something, but is there a standard way to link to other parts of my project? For example, if I am describing my compliance with a control, sometimes I'd like to link part of my project's specification, or a test, or maybe some of the source code. I notice some yaml documents have verification fields with the type TEST; is that part of the standard? We would be happy to contribute some documentation once we have a better understanding.

Also, is there a better place to ask questions that aren't really issues? Do you have a mailing list for OpenControl, for example?

**Comment by jcscottiii** [comment]
@jmacarthur for this type of question you're in the right spot! we do have a general location if you want to check it out: https://github.com/opencontrol/discuss

Yeah, there's a lack of documentation for the `verification` field right now because it's not currently used by masonry.

In addition, to the `verification` field, what you're getting to is the ability to include other files besides the YAML. The answer right now, is you can't :(

https://github.com/opencontrol/compliance-masonry/issues/138
https://github.com/opencontrol/compliance-masonry/issues/131

I hope that answers everything :-/

**Comment by jmacarthur** [comment]
That's fine, we understand that it's a work in progress. Thanks for your quick response!
